name: C CI Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make seq
      run: make seq
    - name: make pthread
      run: make pthread
    - name: make omp
      run: make omp
    - name: make clean
      run: make clean
